[package]
name = "mt-dom"
version = "0.5.2"
authors = [ "Jovansonlee Cesar <ivanceras@gmail.com>" ]
license = "MIT"
description = "A library for diffing virtual dom tree and generate patches"
repository = "https://github.com/ivanceras/sauron"
documentation = "https://docs.rs/mt-dom"
keywords = ["virtual", "dom", "node", "element"]
edition = "2018"

[dependencies]
log = "0.4"

[dev-dependencies]
pretty_env_logger = "0.4"

[features]
with-measure = []
