[package]
name = "mt-dom"
version = "0.2.0"
authors = [ "Jovansonlee Cesar <ivanceras@gmail.com>" ]
license = "MIT"
description = "A library for diffing virtual dom tree and generate patches"
repository = "https://github.com/ivanceras/sauron"
documentation = "https://docs.rs/mt-dom"
keywords = ["virtual", "dom", "node", "element"]
edition = "2018"

[dependencies]
